### ISSUE TITLE
How to set config files 

### ISSUE THREAD

**Issue by simonv3** [loomio/loomio-deploy#39]
Hey, thanks for providing this excellent deploy setup!

I've got loomio running on our server, but we've written a plugin that requires editing the `config/providers.yml` file. I don't think there's an other way of adding to the list of providers, since that's loaded directly from that file in `models/identities/base.rb` so I'm trying to figure out a way of making that file editable on our host without having to go into the container (cause we're likely to forget in that case). 

Specifically we wrote a plugin for adding [Auth0](https://gitlab.com/dsausa/loomio-auth0) to our identity providers, and want to add it to the list of identity providers: 

```
# for providers which provide OAuth login capability
identity:
  - google
  - facebook
  - slack
  - saml
  - auth0

# for providers which provide additional API access
community:
  - facebook
  - slack
```

I've currently created my own file at `config/providers.yml` and edited the `docker-compose.yml` like so:

```
...
app:
  container_name: loomio-app
  restart: always
  image: ${LOOMIO_CONTAINER_IMAGE}:${LOOMIO_CONTAINER_TAG}
  expose:
    - 3000
  env_file: ./env
  links:
    - db
    - redis
  environment:
    - DATABASE_URL=postgresql://postgres:password@db/loomio_production
    - REDIS_URL=redis://redis:6379
  volumes:
    - ./client:/loomio/public/client
    - ./uploads:/loomio/public/system
    - ./files:/loomio/public/files
    - ./plugins:/loomio/plugins/docker
    - ./config/providers.yml:/loomio/config/providers.yml # <--- added this
    - ./import:/import
...
```

but maybe there's a better way?
