### ISSUE TITLE
Trying to deploy on an armv7l server (raspbian/raspberry pi4)

### ISSUE THREAD

**Issue by jimaldon** [loomio/loomio-deploy#68]
Deployment runs until I run the following command
>$ docker-compose --verbose run app rake db:setup

I get the error
`standard_init_linux.go:211: exec user process caused "exec format error"`

I understand it's because the `loomio:loomio/stable docker` image is built for `linux/amd64`. Is there an arm version planned? If not, are there any roadblocks to building it for arm?

**Comment by robguthrie** [comment]
Hi, yes Loomio should run on ARM, but the docker images are compiled for amd64.

To build for ARM:
Checkout this repo (loomio/loomio-deploy) then inside it, check out the loomio/loomio repo into a directory called loomio. 

```
cd loomio-deploy
git clone git@github.com:loomio/loomio.git
git checkout stable
```

Then edit the docker-compose.yml file and comment out (with a # symbol) lines 30 and 51, (the lines which say image: ...) and insert a new line. So it looks a bit like this:

```
app:
  container_name: loomio-app
  restart: always
  # image: ${LOOMIO_CONTAINER_IMAGE}:${LOOMIO_CONTAINER_TAG}
  build: ./loomio

...

worker:
  container_name: loomio-worker
  restart: always
  # image: ${LOOMIO_CONTAINER_IMAGE}:${LOOMIO_CONTAINER_TAG}
  build: ./loomio
```

Docker will then build a custom ARM image for you. If you need to upgrade loomio, run

```
cd loomio-deploy/loomio
git pull origin stable
cd ..
docker-compose build
```

The rest of the upgrade instructions in the README still apply (running migrations etc, shutting down, starting up etc)
